### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by SteffanCline** [ether/pad#313]
I had to adjust some of the paths to get it to this point in the build process. I am stuck at these two errors using scala 2.9.1 compared to the 10 errors with 2.7.7. Any help getting it to build completely on CentOS would be much appreciated.

[root@xx etherpad]# bin/rebuildjar.sh
1.6.0_11
using JAR fastjar...
lib/mysql-connector-java-5.1.12.jar has changed, rebuilding JAR
unzipping JARs...
making cached JAR....
compiling...
compiling with 'scalac'...
using cached common...
using cached sars...
using cached cli...
compiling rhino abstraction...
net.appjet.bodylock/bodylock.scala:70: error: value concat is not a member of List[java.lang.Object with net.appjet.bodylock.JSStackFrame{val code: Array[java.lang.String]; def errorContext(rad: Int): (Int, Int, scala.collection.mutable.WrappedArray[java.lang.String])}]
possible cause: maybe a semicolon is missing before `value concat'?
    }).concat(List(super.frames: _*));
       ^
net.appjet.bodylock/bodylock.scala:150: error: not found: type byte
  def executableFromBytes(bytes: Array[byte], className: String) =
                                       ^
two errors found

Any suggestions on how to get past that point?

Thanks,
Steffan

**Comment by SteffanCline** [comment]
From what I can see on the reference, concat is no longer there. It was back in the day of 2.7.7 but building against that version does not work either.

http://www.scala-lang.org/api/current/index.html#scala.collection.immutable.List

It shows a ++ and flatMap but no concat.

Is this a quick fix and retest? My Java is not that good to test a change.

**Comment by SteffanCline** [comment]
For reference, downgrading to 2.7.0 does not resolve the issue either.

compiling rhino abstraction...
error: error while loading rhinospect, Scala signature rhinospect has wrong version
 expected: 4.1
 found: 5.0
error: error while loading CliOption, Scala signature CliOption has wrong version
 expected: 4.1
 found: 5.0
net.appjet.bodylock/bodylock.scala:219: error: net.appjet.common.cli.CliOption does not have a constructor
      new CliOption(opt._1, opt._3, if (opt._2) Some(opt._4) else None)
      ^
error: error while loading CliParser, Scala signature CliParser has wrong version
 expected: 4.1
 found: 5.0
net.appjet.bodylock/bodylock.scala:242: error: net.appjet.common.cli.CliParser does not have a constructor
    println((new CliParser(options)).usage);
             ^
net.appjet.bodylock/bodylock.scala:245: error: net.appjet.common.cli.CliParser does not have a constructor
    val parser = new CliParser(options);
                 ^
error: error while loading ParseException, Scala signature ParseException has wrong version
 expected: 4.1
 found: 5.0
net.appjet.bodylock/bodylock.scala:251: error: value getMessage is not a member of net.appjet.common.cli.ParseException
          println("error: "+e.getMessage());
                              ^
net.appjet.bodylock/bodylock.scala:257: error: value filter is not a member of Any
    for ((k, v) <- opts) {
         ^
net.appjet.bodylock/bodylock.scala:277: error: value foreach is not a member of Any
    for (p <- args) {
         ^
10 errors found

**Comment by SteffanCline** [comment]
Ok, tried all versions of scala and I get 2,3 and 10 errors. 2 being the least with 2.9.1.

**Comment by rajasaur** [comment]
You might want to try out git://github.com/ijuma/pad.git . Its forked from here but has code that is compatible with scala 2.8 and also works with scala 2.9.0.1 . That repo contains all the patches in https://github.com/ether/pad/pull/179
